<?php

namespace Database\Seeders;

use App\Models\Setting\Module;
use Illuminate\Database\Seeder;

class ModuleSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $module = [
            [
                "id"=> "1",
                "menu"=> "Pembelian",
                "url"=> "#",
                "parent"=> "main",
                "order_number"=> "1",
                "menu_icon"=> "flaticon2-sheet",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "13/10/2020 16:11:38",
                "updated_at"=> "13/10/2020 16:11:38",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "4",
                "menu"=> "pengaturan",
                "url"=> "#",
                "parent"=> "main",
                "order_number"=> "7",
                "menu_icon"=> "flaticon2-gear",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "5",
                "menu"=> "penjualan",
                "url"=> "#",
                "parent"=> "main",
                "order_number"=> "2",
                "menu_icon"=> "flaticon-diagram",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "6",
                "menu"=> "keuangan / accounting",
                "url"=> "#",
                "parent"=> "main",
                "order_number"=> "3",
                "menu_icon"=> "flaticon-price-tag",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "7",
                "menu"=> "persediaan",
                "url"=> "#",
                "parent"=> "main",
                "order_number"=> "4",
                "menu_icon"=> "flaticon2-layers",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "8",
                "menu"=> "Barang",
                "url"=> "#",
                "parent"=> "main",
                "order_number"=> "5",
                "menu_icon"=> "flaticon2-box-1",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "9",
                "menu"=> "pustaka",
                "url"=> "#",
                "parent"=> "main",
                "order_number"=> "6",
                "menu_icon"=> "flaticon2-list-2",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "10",
                "menu"=> "Daftar Pembelian",
                "url"=> "/PurchaseOrder",
                "parent"=> "1",
                "order_number"=> "1",
                "menu_icon"=> "",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "11",
                "menu"=> "Penerimaan Barang",
                "url"=> "/Receiving",
                "parent"=> "1",
                "order_number"=> "2",
                "menu_icon"=> "",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "12",
                "menu"=> "Faktur Pembelian",
                "url"=> "/PurchaseInvoice",
                "parent"=> "1",
                "order_number"=> "3",
                "menu_icon"=> "",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "13",
                "menu"=> "Penawaran",
                "url"=> "/Quotation",
                "parent"=> "5",
                "order_number"=> "1",
                "menu_icon"=> "",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "14",
                "menu"=> "Daftar Penjualan",
                "url"=> "/SalesOrder",
                "parent"=> "5",
                "order_number"=> "2",
                "menu_icon"=> "",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "15",
                "menu"=> "Pengiriman Barang",
                "url"=> "/Delivery",
                "parent"=> "5",
                "order_number"=> "3",
                "menu_icon"=> "",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "sata",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "16",
                "menu"=> "Faktur Penjualan",
                "url"=> "/SalesInvoice",
                "parent"=> "5",
                "order_number"=> "4",
                "menu_icon"=> "",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "sata",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "17",
                "menu"=> "Tukar Faktur",
                "url"=> "/SalesInvoiceCollection",
                "parent"=> "5",
                "order_number"=> "5",
                "menu_icon"=> "",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "sata",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "18",
                "menu"=> "Account Receiveable",
                "url"=> "/AccountReceiveable",
                "parent"=> "6",
                "order_number"=> "1",
                "menu_icon"=> "",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "sata",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "19",
                "menu"=> "Laba / Rugi",
                "url"=> "#",
                "parent"=> "6",
                "order_number"=> "2",
                "menu_icon"=> "",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "20",
                "menu"=> "General Ledger",
                "url"=> "#",
                "parent"=> "6",
                "order_number"=> "3",
                "menu_icon"=> "",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "21",
                "menu"=> "Pengaturan Pelanggan",
                "url"=> "#",
                "parent"=> "6",
                "order_number"=> "4",
                "menu_icon"=> "",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "22",
                "menu"=> "Stok Barang",
                "url"=> "/Stock",
                "parent"=> "7",
                "order_number"=> "1",
                "menu_icon"=> "",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "sata",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "23",
                "menu"=> "Adjustment Stok",
                "url"=> "/Stock/Adjustment",
                "parent"=> "7",
                "order_number"=> "2",
                "menu_icon"=> "",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "sata",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "24",
                "menu"=> "Mutasi Stok",
                "url"=> "/Stock/Mutasi",
                "parent"=> "7",
                "order_number"=> "3",
                "menu_icon"=> "",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "sata",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "25",
                "menu"=> "Daftar Barang",
                "url"=> "/Product",
                "parent"=> "8",
                "order_number"=> "1",
                "menu_icon"=> "",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "26",
                "menu"=> "Harga Barang",
                "url"=> "/ProductPrice",
                "parent"=> "8",
                "order_number"=> "2",
                "menu_icon"=> "",
                "active"=> "N",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "27",
                "menu"=> "Kategori Barang",
                "url"=> "/ProductCategory",
                "parent"=> "8",
                "order_number"=> "3",
                "menu_icon"=> "icon-list-numbered",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "28",
                "menu"=> "Merk Barang",
                "url"=> "/ProductBrand",
                "parent"=> "8",
                "order_number"=> "4",
                "menu_icon"=> "icon-price-tag2",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "29",
                "menu"=> "Satuan",
                "url"=> "/ProductUnit",
                "parent"=> "8",
                "order_number"=> "5",
                "menu_icon"=> "icon-stack-empty",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "30",
                "menu"=> "Keterangan Barang",
                "url"=> "#",
                "parent"=> "8",
                "order_number"=> "6",
                "menu_icon"=> "",
                "active"=> "N",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "4/11/2020 14:13:23",
                "deleted_by"=> "admin",
                "deleted_at"=> "4/11/2020 14:13:23"
            ],
            [
                "id"=> "31",
                "menu"=> "Daftar Pelanggan",
                "url"=> "/Customer",
                "parent"=> "9",
                "order_number"=> "1",
                "menu_icon"=> "",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "32",
                "menu"=> "Kategori Pelanggan",
                "url"=> "/CustomerCategory",
                "parent"=> "9",
                "order_number"=> "2",
                "menu_icon"=> "icon-cart2",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "33",
                "menu"=> "Daftar Supplier",
                "url"=> "/Supplier",
                "parent"=> "9",
                "order_number"=> "3",
                "menu_icon"=> "fa fa-shopping-basket",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "34",
                "menu"=> "Kategori Supplier",
                "url"=> "/SupplierCategory",
                "parent"=> "9",
                "order_number"=> "4",
                "menu_icon"=> "icon-store",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "35",
                "menu"=> "Ekspedisi Pengiriman",
                "url"=> "/Expedition",
                "parent"=> "9",
                "order_number"=> "5",
                "menu_icon"=> "icon-truck",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "36",
                "menu"=> "Daftar Bank",
                "url"=> "/Bank",
                "parent"=> "9",
                "order_number"=> "6",
                "menu_icon"=> "fa fa-bank",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "37",
                "menu"=> "Rekening Perusahaan",
                "url"=> "/CompanyAccount",
                "parent"=> "9",
                "order_number"=> "7",
                "menu_icon"=> "icon-vcard",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "38",
                "menu"=> "Preferensi",
                "url"=> "/Preference",
                "parent"=> "4",
                "order_number"=> "1",
                "menu_icon"=> "icon-vcard",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "39",
                "menu"=> "Daftar Pengguna",
                "url"=> "/Users",
                "parent"=> "4",
                "order_number"=> "2",
                "menu_icon"=> "icon-users4",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "40",
                "menu"=> "Menu",
                "url"=> "/Modules",
                "parent"=> "4",
                "order_number"=> "3",
                "menu_icon"=> "icon-newspaper",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "41",
                "menu"=> "Pengaturan Hak Akses",
                "url"=> "/ModuleAccess",
                "parent"=> "4",
                "order_number"=> "4",
                "menu_icon"=> "icon-user-check",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "42",
                "menu"=> "Profile Saya",
                "url"=> "/Users",
                "parent"=> "4",
                "order_number"=> "5",
                "menu_icon"=> "icon-user",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "14/10/2020 02:10:07",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "43",
                "menu"=> "Ubah Password",
                "url"=> "#",
                "parent"=> "4",
                "order_number"=> "6",
                "menu_icon"=> "",
                "active"=> "N",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 02:10:07",
                "updated_at"=> "3/11/2020 22:30:13",
                "deleted_by"=> "admin",
                "deleted_at"=> "3/11/2020 22:30:13"
            ],
            [
                "id"=> "46",
                "menu"=> "Template Tnc",
                "url"=> "/TermsAndCondTemplate",
                "parent"=> "9",
                "order_number"=> "18",
                "menu_icon"=> "",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "23/11/2020 19:40:23",
                "updated_at"=> "23/11/2020 19:40:23",
                "deleted_by"=> null,
                "deleted_at"=> null
            ],
            [
                "id"=> "47",
                "menu"=> "Daftar Sales",
                "url"=> "/Sales",
                "parent"=> "9",
                "order_number"=> "19",
                "menu_icon"=> "",
                "active"=> "Y",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "1/12/2020 20:33:48",
                "updated_at"=> "1/12/2020 20:33:48",
                "deleted_by"=> null,
                "deleted_at"=> null
            ]
        ];

        Module::insert($module);
    }
}
