<?php

namespace Database\Seeders;

use App\Models\Setting\ModuleAccess;
use Illuminate\Database\Seeder;

class ModuleAccessSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $moduleAccess = [
            [
                "user_id"=> "1",
                "menu_id"=> "1",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "EDIT",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "3",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "4",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "5",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "6",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "7",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "8",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "9",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "10",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "11",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "12",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "13",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "14",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "15",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "16",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "17",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "18",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "19",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "20",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "21",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "22",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "23",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "24",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "25",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "26",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "27",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "28",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "29",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "30",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "31",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "32",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "33",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "34",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "35",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "36",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "37",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "38",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "39",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "40",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "41",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "42",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "43",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "TAMBAH",
                "created_by"=> "admin",
                "updated_by"=> "",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "46",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "EDIT",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ],
            [
                "user_id"=> "1",
                "menu_id"=> "47",
                "add"=> "Y",
                "edit"=> "Y",
                "delete"=> "Y",
                "posting"=> "Y",
                "print"=> "Y",
                "export"=> "Y",
                "approve"=> "Y",
                "active"=> "Y",
                "action"=> "EDIT",
                "created_by"=> "admin",
                "updated_by"=> "admin",
                "created_at"=> "14/10/2020 21:32:46",
                "updated_at"=> "14/10/2020 21:32:46"
            ]
        ];

        ModuleAccess::insert($moduleAccess);
    }
}
